### ISSUE TITLE
sh: 1: ./trans: not found

### ISSUE THREAD

**Issue by ghost** [rpryzant/JESC#1]
I ran the Aligner module, but the ```./trans``` script doesn't exist.
According to the paper, it seems to translate as dictionary lookups.

<blockquote>
(3) translating the Japanese to English with simple dictionary lookups,
</blockquote>

But I'm not sure the exact things.

Could you please explain what ./trans is?

**Comment by rpryzant** [comment]
It's this: https://github.com/soimort/translate-shell
